apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: inventory-service
          imagePullPolicy: Never
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          env:
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: APP_ENV
            - name: SERVICE_MODE
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: INVENTORY_SERVICE_MODE
            - name: TOKEN_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: TOKEN_EXPIRATION
            - name: HTTP_PORT
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: INVENTORY_SERVICE_HTTP_PORT
            - name: GRPC_PORT
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: INVENTORY_SERVICE_GRPC
            - name: GRPC_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: INVENTORY_SERVICE_GRPC_PROTOCOL
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: INVENTORY_SERVICE_MONGO_URI
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: INVENTORY_SERVICE_DATABASE
            - name: PRODUCT_COLLECTION
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: INVENTORY_SERVICE_PRODUCT_COLLECTION
            - name: LOGGER_COLLECTION
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: INVENTORY_SERVICE_DB_LOGGER_COLLECTION
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-srv
spec:
  type: ClusterIP
  selector:
    app: inventory
  ports:
    - name: http
      port: 3000
      targetPort: 3000
